### PR TITLE
TNetXNGFile: explicitly include XrdVersion.hh

### PR DESCRIPTION
**Pull request by veprbl**
Fixes compilation with xrootd v4:

```
/Users/veprbl/root/net/netxng/src/TNetXNGFile.cxx:670:26: error: no member named 'GetDataServer' in 'XrdCl::File'
URL dataServer(fFile->GetDataServer());
~~~~~ ^
1 error generated.
```

### CODE REVIEW

**Comment by veprbl** [comment]
It seems like this was broken since https://github.com/xrootd/xrootd/commit/486911980e2e3689b62263cc156791db59b0ad28

**Comment by karies** [comment]
We have been told:

This has been done since Dec 10, 2014, commits

            master           b4e6255e1b91d9fbc3bfedf270f0135ef12a5b88
            5-34              86a8e2f067a5af613da5217edb26c9adbd092167

How is that insufficient?

Cheers, Axel.

**Comment by veprbl** [comment]
This is sufficient. Thanks. Sorry.
